# [Silah]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [Silah]    Script Date: 3.01.2022 14:12:12 ******/
CREATE DATABASE [Silah]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Silah', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Silah.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Silah_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Silah_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Silah] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Silah].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Silah] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Silah] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Silah] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Silah] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Silah] SET ARITHABORT OFF 
GO
ALTER DATABASE [Silah] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Silah] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Silah] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Silah] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Silah] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Silah] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Silah] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Silah] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Silah] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Silah] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Silah] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Silah] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Silah] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Silah] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Silah] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Silah] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Silah] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Silah] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Silah] SET  MULTI_USER 
GO
ALTER DATABASE [Silah] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Silah] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Silah] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Silah] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Silah] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Silah] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Silah] SET QUERY_STORE = OFF
GO

# [dbo].[AirsoftSilahlari]

In [0]:
USE [Silah]
GO

In [0]:
/****** Object:  Table [dbo].[AirsoftSilahlari]    Script Date: 3.01.2022 14:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AirsoftSilahlari](
	[silahno] [int] NOT NULL,
	[modeladi] [nvarchar](50) NULL,
	[fiyat] [smallmoney] NOT NULL,
	[özellikleri] [nvarchar](50) NULL,
	[stokdurumu] [smallint] NULL,
	[üretimtarihi] [date] NULL,
 CONSTRAINT [PK_AirsoftSilahları] PRIMARY KEY CLUSTERED 
(
	[silahno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[fiyat]

In [0]:
/****** Object:  Table [dbo].[fiyat]    Script Date: 3.01.2022 14:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[fiyat](
	[modelID] [int] NULL,
	[fiyat] [money] NOT NULL
) ON [PRIMARY]
GO

# [dbo].[Giris]

In [0]:
/****** Object:  Table [dbo].[Giris]    Script Date: 3.01.2022 14:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Giris](
	[KulaniciID] [int] NOT NULL,
	[KulanıcıAdi] [nvarchar](50) NOT NULL,
	[MailAdresi] [varchar](50) NOT NULL,
	[Telefon] [numeric](11, 0) NULL,
	[GüvenlikSorusu] [varchar](50) NULL,
	[GüvenlikCevapı] [char](20) NOT NULL,
	[HesapiSilmeTarihi] [date] NOT NULL,
	[SonGirişZamanı] [datetime] NULL,
	[SonHatalıGiriş] [char](10) NULL,
	[HatalıGirişSayisi] [smallint] NULL,
	[Aktifmi] [char](10) NULL
) ON [PRIMARY]
GO

# [dbo].[Kullanici]

In [0]:
/****** Object:  Table [dbo].[Kullanici]    Script Date: 3.01.2022 14:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Kullanici](
	[kulanıcıID] [int] NOT NULL,
	[Adi] [nvarchar](50) NOT NULL,
	[SoyAdi] [nvarchar](50) NOT NULL,
	[KimlikNo] [numeric](11, 0) NOT NULL,
	[DogumTarihi] [date] NOT NULL,
	[AnnesininKızlıkSoyAdi] [nvarchar](50) NOT NULL,
	[MedeniHali] [char](10) NOT NULL,
	[Cinsiyeti] [char](20) NOT NULL,
	[SevdigiYemek] [nvarchar](50) NOT NULL,
	[KayıtTarihi] [date] NOT NULL
) ON [PRIMARY]
GO

# [dbo].[model]

In [0]:
/****** Object:  Table [dbo].[model]    Script Date: 3.01.2022 14:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[model](
	[modelID] [int] NOT NULL,
	[modelAdi] [nvarchar](50) NOT NULL,
	[modelnumarasi] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO

# [dbo].[Ozellikler]

In [0]:
/****** Object:  Table [dbo].[Ozellikler]    Script Date: 3.01.2022 14:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ozellikler](
	[modelID] [int] NULL,
	[Agirlik] [varchar](50) NULL,
	[Kalibre] [char](10) NULL,
	[Kapasite] [varchar](50) NULL,
	[NamluBoyu] [char](20) NULL,
	[ToplamBoy] [varchar](50) NULL,
	[ToplamYukseklik] [varchar](50) NULL,
	[ToplamGenislik] [varchar](30) NULL
) ON [PRIMARY]
GO

# [dbo].[stok]

In [0]:
/****** Object:  Table [dbo].[stok]    Script Date: 3.01.2022 14:12:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[stok](
	[modelID] [int] NULL,
	[StokDurumu] [varchar](50) NULL,
	[StokSayisi] [varchar](50) NULL
) ON [PRIMARY]
GO

# [Silah]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [Silah] SET  READ_WRITE 
GO